package com.mirror.mirrorworld_sdk_android.enums;

public enum DemoAPI {
    //Public
    //Client
    GET_ENVIRONMENT,
    LOGIN_With_EMAIL,
    START_LOGIN,
    IS_LOGGED,
    OPEN_WALLET,
    OPEN_MARKET,
    SET_JWT,
    LOGOUT,
    GUEST_LOGIN,
    FETCH_USER,
    QUERY_USER,

    //EVM >>>>>>>>>

    //Asset/Mint
    CREATE_VERIFIED_COLLECTION,
    MINT_NFT,
    UPDATE_NFT,
    LIST_NFT,
    CANCEL_NFT_LISTING,

    //Confirmation
    CHECK_STATUS_OFMINTING,
    CHECK_STATUS_TRANSACTION,

    FETCH_NFT_BY_CREATOR,
    FETCH_NFT_BY_OWNER_ADDRESSES,
    FETCH_NFT_BY_MINT_ADDRESSES,
    FETCH_NFT_BY_UPDATE_AUTHORITIES,
    FETCH_SINGLE_NFT_DETAILS,
    FETCH_NFT_MARKETPLACE_ACTIVITY,
    TRANSFER_NFT_TO_ANOTHER_WALLET,
    BUY_NFT,

    //wallet
    GET_WALLET_TOKEN,
    GET_TOKENS_BY_WALLET,
    WALLET_TRANSACTIONS,
    WALLET_TRANSACTIONS_BY_WALLET,
    WALLET_TRANSACTIONS_BY_SIGNATURE,
    TRANSFER_SOL,
    TRANSFER_ETH,
    TRANSFER_BNB,
    TRANSFER_MATIC,
    TRANSFER_TOKEN,

    //Metadata
    GET_COLLECTION_FILTER_INFO,
    GET_COLLECTION_INFO,
    METADATA_GET_COLLECTION_SUMMARY,
    SEARCH_NFTS,
    METADATA_GET_NFT_INFO,
    RECOMMEND_SEARCH_NFT,
    METADATA_GET_NFTS_BY_PARAMS,
    GET_NFT_REAL_PRICE,
    GET_NFT_EVENTS,


    //Solana>>>>>>>>>>
    //Asset/Mint
    SOLANA_CREATE_VERIFIED_COLLECTION,
    SOLANA_MINT_NFT,
    SOLANA_UPDATE_NFT,
    SOLANA_LIST_NFT,
    SOLANA_CANCEL_NFT_LISTING,

    //Confirmation
    SOLANA_CHECK_STATUS_OFMINTING,
    SOLANA_CHECK_STATUS_TRANSACTION,

    SOLANA_FETCH_NFT_BY_CREATOR,
    SOLANA_FETCH_NFT_BY_OWNER_ADDRESSES,
    SOLANA_FETCH_NFT_BY_MINT_ADDRESSES,
    SOLANA_FETCH_NFT_BY_UPDATE_AUTHORITIES,
    SOLANA_FETCH_SINGLE_NFT_DETAILS,
    SOLANA_FETCH_NFT_MARKETPLACE_ACTIVITY,
    SOLANA_TRANSFER_NFT_TO_ANOTHER_WALLET,
    SOLANA_BUY_NFT,

    //wallet
    SOLANA_GET_WALLET_TOKEN,
    SOLANA_GET_TOKENS_BY_WALLET,
    SOLANA_WALLET_TRANSACTIONS,
    SOLANA_WALLET_TRANSACTIONS_BY_WALLET,
    SOLANA_WALLET_TRANSACTIONS_BY_SIGNATURE,
    SOLANA_TRANSFER_SOL,
    SOLANA_TRANSFER_ETH,
    SOLANA_TRANSFER_TOKEN,

    //Metadata
    SOLANA_GET_COLLECTION_FILTER_INFO,
    SOLANA_GET_COLLECTION_INFO,
    SOLANA_METADATA_GET_COLLECTION_SUMMARY,
    SOLANA_SEARCH_NFTS,
    SOLANA_METADATA_GET_NFT_INFO,
    SOLANA_RECOMMEND_SEARCH_NFT,
    SOLANA_METADATA_GET_NFTS_BY_PARAMS,
    SOLANA_GET_NFT_REAL_PRICE,
    SOLANA_GET_NFT_EVENTS,
}
