package com.mirror.mirrorworld_sdk_android;

public enum DemoAPI {
    INIT_SDK,
    GET_ENVIRONMENT,
    LOGIN_With_EMAIL,
    START_LOGIN,
    OPEN_WALLET,
    OPEN_MARKET,
    SET_JWT,
    LOGOUT,
    GUEST_LOGIN,
    FETCH_USER,
    QUERY_USER,

    CREATE_VERIFIED_COLLECTION,
    MINT_NFT,
    UPDATE_NFT,
    LIST_NFT,
    UPDATE_NFT_LISTING,
    CANCEL_NFT_LISTING,

    //Confirmation
    CHECK_STATUS_OFMINTING,
    CHECK_STATUS_TRANSACTION,

    FETCH_NFT_BY_OWNER_ADDRESSES,
    FETCH_NFT_BY_MINT_ADDRESSES,
    FETCH_NFT_BY_UPDATE_AUTHORITIES,
    FETCH_SINGLE_NFT_DETAILS,
    FETCH_NFT_MARKETPLACE_ACTIVITY,
    TRANSFER_NFT_TO_ANOTHER_SOLANA_WALLET,
    TRANSFER_SPL_TOKEN,
    BUY_NFT,

    //wallet
    GET_WALLET_TOKEN,
    WALLET_TRANSACTIONS,
    WALLET_TRANSACTIONS_BY_SIGNATURE,
    TRANSFER_SOL,
    WALLET_GET_TRANSACTION_OF_TRANSFER_SOL,
    WALLET_GET_TRANSACTION_OF_TRANSFER_TOKEN,

    GET_COLLECTION_FILTER_INFO,
    GET_NFT_INFO,
    GET_COLLECTION_INFO,
    GET_NFT_EVENTS,
    SEARCH_NFTS,
    RECOMMEND_SEARCH_NFT,
    GET_NFTS,
    GET_NFT_REAL_PRICE,
}
